---
language: php

php:
  - nightly

services:
  - docker

before_install:
  ### install yarn ###
  - sudo apt-get install nodejs npm
  - npm install -g yarn

env:
  PROJECTPORTPREFIX=42

install:
  - make

addons:
  apt:
    update: true
    packages:
      make
