---
language: php

php:
  - '7.3'

services:
  - docker

before_install:
  - nvm install 14.4.0
  - cp website-skeleton/.env.example website-skeleton/.env

env:
  PROJECTPORTPREFIX=42

install:
  - make

addons:
  apt:
    update: true
    packages:
      make
