---
language: php

php:
  - nightly

services:
  - docker

before_install:
  ### install yarn ###
  # - sudo apt-get install npm
  # - npm install -g yarn
  # - echo "node version :"
  - node --version

env:
  PROJECTPORTPREFIX=42
  APP_ENV=dev
  APP_SECRET=73811737aa25c76ad958d30f6c162ee3
  DATABASE_URL="mysql://user:password@127.0.0.1:42306/ezweb_mysql_dev?serverVersion=5.7"
  MAILER_URL=null://localhost
  JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
  JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
  JWT_PASSPHRASE=362dbdbef5397edbd22dab4d5b6e6878
  CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
  LOCK_DSN=semaphore
  SEARCH_ENGINE=legacy
  HTTPCACHE_DEFAULT_TTL=86400
  HTTPCACHE_PURGE_SERVER=http://localhost:80
  HTTPCACHE_VARNISH_INVALIDATE_TOKEN=
  CACHE_POOL=cache.tagaware.filesystem
  CACHE_DSN=localhost
  CACHE_NAMESPACE=ezp
  DATABASE_CHARSET=utf8mb4
  DATABASE_COLLATION=utf8mb4_unicode_520_ci
  DATABASE_VERSION=mariadb-10.3.0
  SESSION_HANDLER_ID=session.handler.native_file
  SESSION_SAVE_PATH=%kernel.project_dir%/var/sessions/%kernel.environment%
  SOLR_DSN=http://localhost:8983/solr
  SOLR_CORE=collection1

install:
  - make

addons:
  apt:
    update: true
    packages:
      make
