---
language: php

php:
  - '7.3'

services:
  - docker

before_install:
  - nvm install 14.4.0
  - cp website-skeleton/.env.example website-skeleton/.env

env:
  PROJECTPORTPREFIX=42
  SYMFONY_VERSION="4.23.2"

install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - make

addons:
  apt:
    update: true
    packages:
      make
