---
language: php

php:
  - '7.3'

services:
  - docker

before_install:
  - nvm install 14.4.0
  - cp website-skeleton/.env.example website-skeleton/.env
  - cd website-skeleton; composer require symfony/framework-bundle:${SYMFONY_VERSION}; cd -
  - ls -la; cd ..; ls -la; cd ..; ls -la; cd ..; ls -la
  - wget https://get.symfony.com/cli/installer -O - | bash
  - mv /home/Avocalypse/.symfony/bin/symfony /usr/local/bin/symfony

env:
  PROJECTPORTPREFIX=42
  SYMFONY_VERSION="4.23.2"

install:
  - make

addons:
  apt:
    update: true
    packages:
      make
