---
language: php

php:
  - '7.3'

services:
  - docker

before_install:
  - nvm install 14.4.0
  - cd website-skeleton; cp .env.example .env

env:
  PROJECTPORTPREFIX=42

install:
  - make

addons:
  apt:
    update: true
    packages:
      make
