version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: ezweb_mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: ezweb_mysql_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - ${PROJECTPORTPREFIX}306:3306
    expose:
      - ${PROJECTPORTPREFIX}306
    volumes:
      - 'mysql-volume:/var/lib/ezweb_mysql/data'

  redis:
    image: redis:alpine
    container_name: ezweb_redis
    ports:
      - "${PROJECTPORTPREFIX}379:6379"
    restart: on-failure

  mailcatcher:
    image: dockage/mailcatcher:0.7.1
    container_name: ezweb_mailcatcher
    ports:
      - "${PROJECTPORTPREFIX}080:1080"
      - "${PROJECTPORTPREFIX}025:1025"
    restart: on-failure
  
volumes:
  mysql-volume:
